services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - weixing-network
  websocket-server:
    image: yijun9124/weixing-websocket-server:${TAG:-latest}
    container_name: websocket-server
    hostname: websocket-server
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:${WS_PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - weixing-network
  udp-server:
    image: yijun9124/weixing-udp-server:${TAG:-latest}
    container_name: udp-server
    hostname: udp-server
    restart: unless-stopped
    ports:
      - "2000:2000/udp"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
    networks:
      - weixing-network
  tcp-server:
    image: yijun9124/weixing-tcp-server:${TAG:-latest}
    container_name: tcp-server
    hostname: tcp-server
    restart: unless-stopped
    ports:
      - "8999:8999"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
      - ./error:/usr/src/app/error
      - ./temp:/usr/src/app/temp
    networks:
      - weixing-network
  backend-service:
    image: yijun9124/weixing-service:${TAG:-latest}
    container_name: backend-service
    hostname: backend-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    devices:
      - "/dev/ttyS2:/dev/ttyS2"
      - "/dev/ttyS3:/dev/ttyS3"
    privileged: true
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://backend-service:3000/api/parameters",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - weixing-network
  frontend:
    image: yijun9124/weixing-frontend:${TAG:-latest}
    container_name: frontend
    hostname: frontend
    restart: unless-stopped
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - weixing-network

networks:
  weixing-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
